namespace DentalClinic.DTOs.ReportDTO
{
    public class ProcedureRevenue
    {
        public string Procedure { get; set; } // Name of the procedure
        public decimal Revenue { get; set; } // Revenue generated by the procedure
    }

}
